branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - ci
      enforce_admins: true
      restrictions:
        teams: []
        users: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false