on:
  pull_request:
  push:
    branches: [main, dev, feature/*]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      
      # - name: Build Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     load: true
      #     tags: app:test
      
      # - name: Run tests in container
      #   run: docker run --rm app:test npm test

      - name: Build Docker image
        run: docker build -t mon-app .

      - name: Run container to test it
        run: docker run --rm -d -p 3000:3000 --name test-container mon-app

      - name: Check if container is running
        run: docker ps | grep test-container

      - name: Stop and clean container
        run: docker stop test-container

  cd:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-ex1:latest
      
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"